// Generated by tools/gen_packet_wire.py - do not edit
#if !defined(_WIN32)

#include "stdafx.h"
#include "PacketWireLayout.h"
#include "NtlSharedCommon.h"

static const unsigned int PACKET_WIRE_MAX_OPS = 32;

typedef struct {
  unsigned int wire_size;
  unsigned int our_size;
  unsigned int n_ops;
  unsigned int wire_off[32];
  unsigned int our_off[32];
  unsigned int len[32];
} packet_wire_row_t;

static const packet_wire_row_t PACKET_WIRE_TABLE[] = {
  { 795, 839, 12, { 0, 63, 65, 138, 211, 284, 357, 430, 503, 576, 649, 722, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 }, { 0, 67, 69, 146, 223, 300, 377, 454, 531, 608, 685, 762, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 }, { 63, 2, 73, 73, 73, 73, 73, 73, 73, 73, 73, 73, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 } },
  { 23, 23, 1, { 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 }, { 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 }, { 23, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 } },
  { 2, 2, 1, { 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 }, { 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 }, { 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 } },
  { 2, 2, 1, { 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 }, { 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 }, { 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 } },
  { 48, 48, 1, { 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 }, { 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 }, { 48, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 } },
  { 4, 4, 1, { 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 }, { 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 }, { 4, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 } },
  { 4, 4, 1, { 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 }, { 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 }, { 4, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 } },
};

static const unsigned int PACKET_WIRE_TABLE_OPCODES[] = {
  1002, 2001, 2002, 2003, 2004, 3005, 3006
};
static const unsigned int PACKET_WIRE_TABLE_COUNT = 7;

static const packet_wire_row_t* find_row(unsigned int wOpCode) {
  for (unsigned int i = 0; i < PACKET_WIRE_TABLE_COUNT; i++) {
    if (PACKET_WIRE_TABLE_OPCODES[i] == wOpCode)
      return &PACKET_WIRE_TABLE[i];
  }
  return NULL;
}

unsigned int PacketWire_GetWirePayloadSize(unsigned int wOpCode) {
  const packet_wire_row_t* r = find_row(wOpCode);
  return r ? r->wire_size : 0;
}

unsigned int PacketWire_GetOurPayloadSize(unsigned int wOpCode) {
  const packet_wire_row_t* r = find_row(wOpCode);
  return r ? r->our_size : 0;
}

unsigned int PacketWire_EncodePayload(unsigned int wOpCode,
  const unsigned char* pOurPayload, unsigned int ourPayloadSize,
  unsigned char* pWirePayload, unsigned int wirePayloadSize) {
  const packet_wire_row_t* r = find_row(wOpCode);
  if (!r || r->wire_size > wirePayloadSize || r->our_size > ourPayloadSize) return 0;
  for (unsigned int i = 0; i < r->n_ops; i++) {
    CopyMemory(pWirePayload + r->wire_off[i], pOurPayload + r->our_off[i], r->len[i]);
  }
  return r->wire_size;
}

unsigned int PacketWire_DecodePayload(unsigned int wOpCode,
  const unsigned char* pWirePayload, unsigned int wirePayloadSize,
  unsigned char* pOurPayload, unsigned int ourPayloadSize) {
  const packet_wire_row_t* r = find_row(wOpCode);
  if (!r || r->wire_size > wirePayloadSize || r->our_size > ourPayloadSize) return 0;
  ZeroMemory(pOurPayload, r->our_size);
  for (unsigned int i = 0; i < r->n_ops; i++) {
    CopyMemory(pOurPayload + r->our_off[i], pWirePayload + r->wire_off[i], r->len[i]);
  }
  return r->our_size;
}

#else
// Windows: pass-through
unsigned int PacketWire_GetWirePayloadSize(unsigned int wOpCode) { (void)wOpCode; return 0; }
unsigned int PacketWire_GetOurPayloadSize(unsigned int wOpCode) { (void)wOpCode; return 0; }
unsigned int PacketWire_EncodePayload(unsigned int wOpCode,
  const unsigned char* pOurPayload, unsigned int ourPayloadSize,
  unsigned char* pWirePayload, unsigned int wirePayloadSize) {
  (void)wOpCode; (void)ourPayloadSize;
  if (pOurPayload && pWirePayload && wirePayloadSize >= ourPayloadSize) {
    CopyMemory(pWirePayload, pOurPayload, ourPayloadSize);
    return ourPayloadSize;
  }
  return 0;
}
unsigned int PacketWire_DecodePayload(unsigned int wOpCode,
  const unsigned char* pWirePayload, unsigned int wirePayloadSize,
  unsigned char* pOurPayload, unsigned int ourPayloadSize) {
  (void)wOpCode; (void)wirePayloadSize;
  if (pWirePayload && pOurPayload && ourPayloadSize >= wirePayloadSize) {
    CopyMemory(pOurPayload, pWirePayload, wirePayloadSize);
    return wirePayloadSize;
  }
  return 0;
}
#endif