#pragma once

// One-shot generated wire layer: encode (our layout -> wire) and decode (wire -> our layout)
// so send/recv match the Windows client. Table and logic are in PacketWireLayout.generated.cpp
// (generated by tools/gen_packet_wire.py from config/wire_layout.txt + config/our_layout.txt).
// No per-packet wire code; one mechanism for all packets.

// Returns wire payload size for opcode; 0 = pass-through (use packet size as-is).
unsigned int PacketWire_GetWirePayloadSize(unsigned int wOpCode);

// Returns our (Linux) payload size for opcode when we receive wire bytes; 0 = pass-through.
unsigned int PacketWire_GetOurPayloadSize(unsigned int wOpCode);

// Encode: our payload -> wire payload. Returns encoded wire payload size, or 0 on error / pass-through.
unsigned int PacketWire_EncodePayload(unsigned int wOpCode,
	const unsigned char* pOurPayload, unsigned int ourPayloadSize,
	unsigned char* pWirePayload, unsigned int wirePayloadSize);

// Decode: wire payload -> our payload. pOurPayload must be zeroed or valid. Returns our payload size, or 0.
unsigned int PacketWire_DecodePayload(unsigned int wOpCode,
	const unsigned char* pWirePayload, unsigned int wirePayloadSize,
	unsigned char* pOurPayload, unsigned int ourPayloadSize);
