[Auth Server]
Address = 172.28.112.18
Port = 20210
ServerID = 0

[DATABASE_ACCOUNT]
Host = 127.0.0.1
User = dbod
Password = strongpassword
Db = dbod_acc
Log = dbod_log

[Master Connect]
;server connect to master server
Address = 127.0.0.1
Port = 40011


[CONFIG]
;BOOL - If 1 then only gm's allowed to connect
DisableConnection = 0
MaxConnection = 5
;BOOL - If 1 then founder people can connect (only apply when DisableConnection is 1)
FounderConnection = 0