[Chat Server]
Address = 0.0.0.0
PublicAddress = 0.0.0.0
Port = 20410
server_accept_limit = 5
Server_Accept_Address = 0.0.0.0
Server_Accept_Port = 21410

[Master Connect]
Address = 127.0.0.1
Port = 40013

[Query Connect]
Address = 127.0.0.1
Port = 41010

[DATABASE_CHARACTER]
Host = 127.0.0.1
User = dbod
Password = strongpassword
Db = dbod_char
Log = dbod_log

[DATABASE_ACCOUNT]
Host = 127.0.0.1
User = dbod
Password = strongpassword
Db = dbod_acc

[CONFIG]
MaxConnection = 10

[TABLE]
LoadTableFormat = 1
; 0 = XML, 1 = Binary(rdf), 2 = Secured Binary(edf)
Path = ../resource/server_data/table/rdf