#include "StdAfx.h"
#include "NtlPacketMG.h"


const char * s_packetName_MG[] =
{
	DECLARE_PACKET_NAME( MG_HEARTBEAT ),
	DECLARE_PACKET_NAME( MG_AUTH_SERVER_FARM_INFO ),
	DECLARE_PACKET_NAME( MG_CHARACTER_SERVER_FARM_INFO ),
	DECLARE_PACKET_NAME( MG_GAME_SERVER_FARM_INFO ),
	DECLARE_PACKET_NAME( MG_GAME_SERVER_CHANNEL_INFO ),
	DECLARE_PACKET_NAME( MG_SERVERS_INFO ),
	DECLARE_PACKET_NAME( MG_SERVICE_INFO ),
	DECLARE_PACKET_NAME( MG_WORLD_ASSIGNMENT_INFO_BEGIN ),
	DECLARE_PACKET_NAME( MG_WORLD_ASSIGNMENT_INFO ),
	DECLARE_PACKET_NAME( MG_WORLD_ASSIGNMENT_INFO_END ),
	DECLARE_PACKET_NAME( MG_SERVERS_INFO_END ),
	DECLARE_PACKET_NAME( MG_NOTIFY_ILLEGAL_SERVER ),

	DECLARE_PACKET_NAME( MG_SERVER_INFO_CHANGED_NFY ),
	DECLARE_PACKET_NAME( MG_AUTH_SERVER_FARM_INFO_CHANGED_NFY ),
	DECLARE_PACKET_NAME( MG_CHARACTER_SERVER_FARM_INFO_CHANGED_NFY ),

	DECLARE_PACKET_NAME( MG_GAME_SERVER_FARM_INFO_CHANGED_NFY ),
	DECLARE_PACKET_NAME( MG_GAME_SERVER_CHANNEL_INFO_CHANGED_NFY ),

	DECLARE_PACKET_NAME( MG_SERVER_USER_ALL_KICK_REQ ),
	DECLARE_PACKET_NAME( MG_SERVER_VERSION_CHANGED_NFY ), // by sooshia 07/23/2008
	DECLARE_PACKET_NAME( MG_SERVER_TURNOFF_FOR_DEVEL_NFY ),
	DECLARE_PACKET_NAME( MG_SERVER_MAX_USER_NFY ),
	DECLARE_PACKET_NAME( MG_LOGIN_RES ),
	DECLARE_PACKET_NAME( MG_MOVE_RES ),
	DECLARE_PACKET_NAME( MG_KICKOUT_REQ ),

	DECLARE_PACKET_NAME( MG_PING_RES ),

	DECLARE_PACKET_NAME( MG_REPORT_MONSTER_STATISTICS_CONTINUE_REQ ),
	DECLARE_PACKET_NAME( MG_PLAYER_SWITCH_CHANNEL_RES ),
	DECLARE_PACKET_NAME( MG_PLAYER_EXIT_TO_CHAR_RES ),

	DECLARE_PACKET_NAME( MG_SERVERS_INFO_ADD ),
	DECLARE_PACKET_NAME( MG_WEB_ONLINE_PLAYERS_REQ ),
	DECLARE_PACKET_NAME( MG_WEB_SEND_NOTICE_REQ ),
	DECLARE_PACKET_NAME( MG_WEB_KICK_PLAYER_REQ ),
	DECLARE_PACKET_NAME( MG_WEB_GIVE_ITEM_REQ ),
	DECLARE_PACKET_NAME( MG_WEB_GIVE_ITEM_ALL_REQ ),
	DECLARE_PACKET_NAME( MG_WEB_EXEC_GM_COMMAND_REQ ),
	DECLARE_PACKET_NAME( MG_WEB_APPLY_BUFF_REQ ),
	DECLARE_PACKET_NAME( MG_WEB_REMOVE_BUFF_SKILL_REQ ),
	DECLARE_PACKET_NAME( MG_WEB_REMOVE_BUFF_EFFECT_REQ ),
	DECLARE_PACKET_NAME( MG_WEB_CLEAR_BUFFS_REQ ),
	DECLARE_PACKET_NAME( MG_WEB_HEAL_FULL_REQ ),
	DECLARE_PACKET_NAME( MG_WEB_ADD_ZENI_REQ ),
	DECLARE_PACKET_NAME( MG_WEB_GIVE_ITEM_CUSTOM_REQ ),
	DECLARE_PACKET_NAME( MG_WEB_APPLY_BUFF_SKILL_ALL_REQ ),
	DECLARE_PACKET_NAME( MG_WEB_APPLY_BUFF_ITEM_REQ ),
	DECLARE_PACKET_NAME( MG_WEB_APPLY_BUFF_ITEM_ALL_REQ ),
	DECLARE_PACKET_NAME( MG_WEB_REMOVE_BUFF_SKILL_ALL_REQ ),
	DECLARE_PACKET_NAME( MG_WEB_REMOVE_BUFF_EFFECT_ALL_REQ ),
	DECLARE_PACKET_NAME( MG_WEB_CLEAR_BUFFS_ALL_REQ ),
	DECLARE_PACKET_NAME( MG_WEB_SET_LEVEL_REQ ),
	DECLARE_PACKET_NAME( MG_WEB_SET_CLASS_REQ ),
	DECLARE_PACKET_NAME( MG_WEB_KILL_PLAYER_REQ ),
	DECLARE_PACKET_NAME( MG_WEB_TELEPORT_PORTAL_REQ ),
	DECLARE_PACKET_NAME( MG_WEB_TELEPORT_WORLD_REQ ),
	DECLARE_PACKET_NAME( MG_WEB_TELEPORT_COORDS_REQ ),
	DECLARE_PACKET_NAME( MG_WEB_MUTE_PLAYER_REQ ),
	DECLARE_PACKET_NAME( MG_WEB_UNMUTE_PLAYER_REQ ),
	DECLARE_PACKET_NAME( MG_WEB_TOGGLE_EXP_REQ ),
	DECLARE_PACKET_NAME( MG_WEB_RESET_EXP_REQ ),
	DECLARE_PACKET_NAME( MG_WEB_LEARN_SKILL_REQ ),
	DECLARE_PACKET_NAME( MG_WEB_ADD_TITLE_REQ ),
	DECLARE_PACKET_NAME( MG_WEB_REMOVE_TITLE_REQ ),
	DECLARE_PACKET_NAME( MG_WEB_SET_SOLO_EXP_BONUS_REQ ),
	DECLARE_PACKET_NAME( MG_WEB_SET_PARTY_EXP_BONUS_REQ ),
	DECLARE_PACKET_NAME( MG_WEB_SET_QUEST_EXP_BONUS_REQ ),
	DECLARE_PACKET_NAME( MG_WEB_SET_CRAFT_EXP_BONUS_REQ ),
	DECLARE_PACKET_NAME( MG_WEB_SET_ZENI_DROP_BONUS_REQ ),
	DECLARE_PACKET_NAME( MG_WEB_SET_QUEST_MONEY_BONUS_REQ ),
	DECLARE_PACKET_NAME( MG_WEB_SET_UPGRADE_RATE_BONUS_REQ ),
	DECLARE_PACKET_NAME( MG_WEB_SET_MONSTER_AGGRESSIVE_REQ ),
	DECLARE_PACKET_NAME( MG_WEB_SET_MONSTER_STAT_BONUS_REQ ),
	DECLARE_PACKET_NAME( MG_WEB_APPLY_MONSTER_BUFF_SKILL_ALL_REQ ),
	DECLARE_PACKET_NAME( MG_WEB_CLEAR_MONSTER_BUFFS_ALL_REQ ),
	DECLARE_PACKET_NAME( MG_WEB_SET_KILL_DEBUFF_REQ ),
	DECLARE_PACKET_NAME( MG_WEB_RESET_SKILL_COOLDOWN_REQ ),
	DECLARE_PACKET_NAME( MG_WEB_RESET_SKILL_COOLDOWN_ALL_REQ ),
	DECLARE_PACKET_NAME( MG_WEB_SET_CHANNEL_STAT_BONUS_REQ ),
};


//------------------------------------------------------------------
//
//------------------------------------------------------------------
const char * NtlGetPacketName_MG(WORD wOpCode)
{
	if( wOpCode < MG_OPCODE_BEGIN )
	{
		return "NOT DEFINED PACKET NAME : OPCODE LOW";
	}

	if( wOpCode > MG_OPCODE_END )
	{
		return "NOT DEFINED PACKET NAME : OPCODE HIGH";
	}

	int nIndex = wOpCode - MG_OPCODE_BEGIN;
	if( nIndex >= _countof( s_packetName_MG) )
	{
		return "OPCODE BUFFER OVERFLOW";
	}

	return s_packetName_MG[ nIndex ];
}