#include "stdafx.h"
#include "NtlPacketGM.h"

const char * s_packetName_GM[] =
{
	DECLARE_PACKET_NAME( GM_NOTIFY_SERVER_BEGIN ),
	DECLARE_PACKET_NAME( GM_HEARTBEAT ),
	DECLARE_PACKET_NAME( GM_REPORT_LOAD ),
	DECLARE_PACKET_NAME( GM_REPORT_CONNECTED_USER_INFO ),

	DECLARE_PACKET_NAME( GM_REPORT_MONSTER_STATISTICS_BEGIN ),
	DECLARE_PACKET_NAME( GM_REPORT_MONSTER_STATISTICS ),
	DECLARE_PACKET_NAME( GM_REPORT_MONSTER_STATISTICS_SENDING_PAUSED_NFY ),
	DECLARE_PACKET_NAME( GM_REPORT_MONSTER_STATISTICS_END ),

	DECLARE_PACKET_NAME( GM_USERCOUNT_RES ),
	DECLARE_PACKET_NAME( GM_SERVER_CONTROL_TURN_OFF_ALL_NFY ),
	DECLARE_PACKET_NAME( GM_LOGIN_REQ ),
	DECLARE_PACKET_NAME( GM_LOGOUT_REQ ),
	DECLARE_PACKET_NAME( GM_MOVE_REQ ),
	DECLARE_PACKET_NAME( GM_KICKOUT_RES ),	
	DECLARE_PACKET_NAME( GM_ON_PLAYER_INFO ),
	DECLARE_PACKET_NAME( GM_PING_REQ ),
	DECLARE_PACKET_NAME( GM_PLAYER_SWITCH_CHANNEL_REQ ),
	DECLARE_PACKET_NAME( GM_PLAYER_EXIT_TO_CHAR_REQ ),
	DECLARE_PACKET_NAME(GM_SERVER_SHUT_DOWN),
	DECLARE_PACKET_NAME( GM_WEB_ONLINE_PLAYERS_RES ),
	DECLARE_PACKET_NAME( GM_WEB_SEND_NOTICE_RES ),
	DECLARE_PACKET_NAME( GM_WEB_KICK_PLAYER_RES ),
	DECLARE_PACKET_NAME( GM_WEB_GIVE_ITEM_RES ),
	DECLARE_PACKET_NAME( GM_WEB_GIVE_ITEM_ALL_RES ),
	DECLARE_PACKET_NAME( GM_WEB_EXEC_GM_COMMAND_RES ),
	DECLARE_PACKET_NAME( GM_WEB_APPLY_BUFF_RES ),
	DECLARE_PACKET_NAME( GM_WEB_REMOVE_BUFF_SKILL_RES ),
	DECLARE_PACKET_NAME( GM_WEB_REMOVE_BUFF_EFFECT_RES ),
	DECLARE_PACKET_NAME( GM_WEB_CLEAR_BUFFS_RES ),
	DECLARE_PACKET_NAME( GM_WEB_HEAL_FULL_RES ),
	DECLARE_PACKET_NAME( GM_WEB_ADD_ZENI_RES ),
	DECLARE_PACKET_NAME( GM_WEB_GIVE_ITEM_CUSTOM_RES ),
	DECLARE_PACKET_NAME( GM_WEB_APPLY_BUFF_SKILL_ALL_RES ),
	DECLARE_PACKET_NAME( GM_WEB_APPLY_BUFF_ITEM_RES ),
	DECLARE_PACKET_NAME( GM_WEB_APPLY_BUFF_ITEM_ALL_RES ),
	DECLARE_PACKET_NAME( GM_WEB_REMOVE_BUFF_SKILL_ALL_RES ),
	DECLARE_PACKET_NAME( GM_WEB_REMOVE_BUFF_EFFECT_ALL_RES ),
	DECLARE_PACKET_NAME( GM_WEB_CLEAR_BUFFS_ALL_RES ),
	DECLARE_PACKET_NAME( GM_WEB_SET_LEVEL_RES ),
	DECLARE_PACKET_NAME( GM_WEB_SET_CLASS_RES ),
	DECLARE_PACKET_NAME( GM_WEB_KILL_PLAYER_RES ),
	DECLARE_PACKET_NAME( GM_WEB_TELEPORT_PORTAL_RES ),
	DECLARE_PACKET_NAME( GM_WEB_TELEPORT_WORLD_RES ),
	DECLARE_PACKET_NAME( GM_WEB_TELEPORT_COORDS_RES ),
	DECLARE_PACKET_NAME( GM_WEB_MUTE_PLAYER_RES ),
	DECLARE_PACKET_NAME( GM_WEB_UNMUTE_PLAYER_RES ),
	DECLARE_PACKET_NAME( GM_WEB_TOGGLE_EXP_RES ),
	DECLARE_PACKET_NAME( GM_WEB_RESET_EXP_RES ),
	DECLARE_PACKET_NAME( GM_WEB_LEARN_SKILL_RES ),
	DECLARE_PACKET_NAME( GM_WEB_ADD_TITLE_RES ),
	DECLARE_PACKET_NAME( GM_WEB_REMOVE_TITLE_RES ),
	DECLARE_PACKET_NAME( GM_WEB_SET_SOLO_EXP_BONUS_RES ),
	DECLARE_PACKET_NAME( GM_WEB_SET_PARTY_EXP_BONUS_RES ),
	DECLARE_PACKET_NAME( GM_WEB_SET_QUEST_EXP_BONUS_RES ),
	DECLARE_PACKET_NAME( GM_WEB_SET_CRAFT_EXP_BONUS_RES ),
	DECLARE_PACKET_NAME( GM_WEB_SET_ZENI_DROP_BONUS_RES ),
	DECLARE_PACKET_NAME( GM_WEB_SET_QUEST_MONEY_BONUS_RES ),
	DECLARE_PACKET_NAME( GM_WEB_SET_UPGRADE_RATE_BONUS_RES ),
	DECLARE_PACKET_NAME( GM_WEB_SET_MONSTER_AGGRESSIVE_RES ),
	DECLARE_PACKET_NAME( GM_WEB_SET_MONSTER_STAT_BONUS_RES ),
	DECLARE_PACKET_NAME( GM_WEB_APPLY_MONSTER_BUFF_SKILL_ALL_RES ),
	DECLARE_PACKET_NAME( GM_WEB_CLEAR_MONSTER_BUFFS_ALL_RES ),
	DECLARE_PACKET_NAME( GM_WEB_SET_KILL_DEBUFF_RES ),
	DECLARE_PACKET_NAME( GM_WEB_RESET_SKILL_COOLDOWN_RES ),
	DECLARE_PACKET_NAME( GM_WEB_RESET_SKILL_COOLDOWN_ALL_RES ),
	DECLARE_PACKET_NAME( GM_WEB_SET_CHANNEL_STAT_BONUS_RES ),

};


//------------------------------------------------------------------
//
//------------------------------------------------------------------
const char * NtlGetPacketName_GM(WORD wOpCode)
{
	if( wOpCode < GM_OPCODE_BEGIN )
	{
		return "NOT DEFINED PACKET NAME : OPCODE LOW";
	}

	if( wOpCode > GM_OPCODE_END )
	{
		return "NOT DEFINED PACKET NAME : OPCODE HIGH";
	}

	int nIndex = wOpCode - GM_OPCODE_BEGIN;
	if( nIndex >= _countof( s_packetName_GM) )
	{
		return "OPCODE BUFFER OVERFLOW";
	}

	return s_packetName_GM[ nIndex ];
}
